

const CountryList = [
    "Andorra",
    "Angola",
    "Anguilla",
    "Argentina",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Belgium",
    "Benin",
    "Bermuda",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Chad",
    "Chile",
    "China",
    "Crotia",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Gibraltar",
    "Greece",
    "Guam",
    "Guatemala",
    "Guernsey and Alderney",
    "Hong Kong S.A.R",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Ireland",
    "Isreal",
    "Italy",
    "Japan",
    "Jersey",
    "Jordan",
    "Kenya",
    "North Korea",
    "South Korea",
    "Latvia",
    "Liechenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Malta",
    "Man (Isle of)",
    "Mexico",
    "Monaco",
    "Mozambique",
    "Netherlands",
    "New Zealand",
    "Niger",
    "Norway",
    "Peru",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Romania",
    "San Marino",
    "Senegal",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Tanzania",
    "Thailand",
    "Turkey",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uzbekistan"
]

export default CountryList